server:
  port: 9002

#注册进服务中心
eureka:
  client:
    serviceUrl:
#      defaultZone: http://172.17.0.2:9003/eureka/
      defaultZone: http://localhost:9003/eureka/
#显示版本号信息，服务器ip地址和端口
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

spring:
    application:
        name: tqfframe-config
    cloud:
        config:
            label: master
            server:
                git:
                    password: tangqifeng481
                    # tqfframe-config-yaml/test表示
                    # https://github.com/448915931/newtqffram/tqfframe-config-yaml/test
#                    searchPaths: tqfframe-config-yaml/product
                    searchPaths: tqfframe-config-yaml/office
                    #使用远程git仓库的配置文件
                    uri: https://github.com/448915931/newtqffram.git
                    username: 448915931
