server:
  port: 9001
spring:
  application:
    name: tqfframe-website
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: root
    password: 123456


#tang: 3