server:
  port: 9007
spring:
  application:
    name: tqfframe-app
  datasource:
    url: jdbc:mysql://192.168.47.137:3306/testDB?characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: tangqifeng
    password: 123456


#tang: 3