server:
  port: 9091
#  servlet: //项目根目录
#    context-path: /api

spring:
  application:
    name: tqfframe-website

#注册进服务中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9003/eureka/
#显示版本号信息，服务器ip地址和端口
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2




