eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
#  server:
#    enable-self-preservation: true
#    response-cache-auto-expiration-in-seconds: 15
#    eviction-interval-timer-in-ms: 1000
  client:
    #由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    register-with-eureka: false
     #由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
server:
  port: 9003
spring:
  application:
    name: registry
